version: '3.1'

services:
    app:
        build:
            context: docker/local
            dockerfile: app.docker
        volumes:
            - ./:/var/www/html
            - ./docker/local/apache2log/:/var/log/apache2
        ports:
            - "80:80"
            - "3000:3000"
        depends_on:
            - database
        links:
            - database
            - mailhog
            # - selenium
        # networks:
        #     - laravel-inertia
    database:
        image: postgres:14-alpine
        environment:
            - "POSTGRES_PASSWORD=${DB_PASSWORD}"
            - "POSTGRES_DB=db"
        ports:
            - "54321:5432"
        volumes:
            - argon_pgdata:/var/lib/postgresql/data/
        # networks:
        #     - laravel-inertia
    selenium:
        image: 'selenium/standalone-chrome'
        volumes:
            - '/dev/shm:/dev/shm'
        depends_on:
            - app
        links:
            - app
        ports:
            - "8080:4444"
        expose:
            - 4444

        # networks:
        #     - laravel-inertia

    mailhog:
        image: mailhog/mailhog
        ports:
            - "8025:8025"
        # networks:
        #     - laravel-inertia
volumes:
    argon_pgdata:
        # networks:
        #     default:
        #         name: laravel-inertia
        # networks:
        #   default:
        #     external:
        #       name: laravel-inertia

